apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-terminator
subjects:
- kind: ServiceAccount
  name: pod-terminator
  namespace: pod-terminator
roleRef:
  kind: ClusterRole
  name: pod-terminator
  apiGroup: rbac.authorization.k8s.io