apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: pod-terminator
  name: pod-terminator
  namespace: pod-terminator
spec:
  successfulJobsHistoryLimit: 1
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pod-terminator
            image: ghcr.io/stevedetm/restart-pod-job:latest
          serviceAccountName: pod-terminator
          restartPolicy: OnFailure