apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: pod-terminator
  name: pod-terminator
  namespace: pod-terminator
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        metadata: 
          annotations:
            argocd.argoproj.io/hook: PostSync  
            argocd.argoproj.io/hook-delete-policy: HookSucceeded
        spec:
          containers:
          - name: pod-terminator
            image: ghcr.io/stevedetm/restart-pod-job:latest
          serviceAccountName: pod-terminator
          restartPolicy: OnFailure